import Head from 'next/head'
import { useTranslation, Trans } from 'next-i18next'
import { loadTranslation } from "../i18n";

export const getStaticProps = async (context: any) => {
  const cart = [
    {
      name: "Fiji water",
      count: 4,
    }, 
    {
      name: "Meji chocolate",
      count: 8
    },
    {
      name: "Macbook Pro M2",
      count: 1
    }
  ]
  const translation = await loadTranslation(
    context.locale!,
    "home"
  )

  return {
    props: {
      list: cart,
      ...translation, // Important to use ...translation
    },
  };
}

export default function Home(props: any) {
  const { t } = useTranslation("home")
  const { list } = props

  return (
    <>
      <Head>
        <title>{t("home:title", { defaultValue: "Create Next App" })}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Trans i18nKey={"home:txt"}>This is a Test</Trans>
      </div>
      <div>
        {list.map((v: any, i: number) => {
          return <li key={i} style={{width: "280px", display: "flex", margin: "10px"}}>
                <div style={{width: "100%"}}>
                  <span style={{marginRight: "10px"}}>
                      <Trans i18nKey={"home:listItem"}>Purchased {{ item: v.name }}</Trans>
                  </span>
                  {`    -    `}
                  <span style={{marginLeft: "10px"}}>
                  {t("home:itemCount", "{{ count }} unit", {
                    count: v.count,
                    defaultValue_other: "{{ count }} units"
                  })}
                  </span>
                </div>
              </li>
        })}
      </div>
    </>
  )
}
